# Generated by Django 2.1 on 2020-03-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailypost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('code', models.CharField(max_length=32)),
            ],
        ),
    ]
