# Generated by Django 2.1 on 2020-03-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailypost', '0002_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='code',
            new_name='codemodel',
        ),
    ]
