# Generated by Django 2.1 on 2020-03-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailypost', '0004_auto_20200323_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypost',
            name='ip',
            field=models.GenericIPAddressField(default=''),
        ),
    ]
