# Generated by Django 2.1 on 2020-04-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailypost', '0005_dailypost_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='codemodel',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
