# Generated by Django 2.1 on 2020-04-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailypost', '0006_codemodel_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codemodel',
            name='url',
        ),
        migrations.AddField(
            model_name='codemodel',
            name='img',
            field=models.ImageField(default=' ', upload_to='img'),
        ),
    ]
