# Generated by Django 2.1 on 2020-04-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailypost', '0007_auto_20200420_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codemodel',
            name='img',
        ),
        migrations.AddField(
            model_name='codemodel',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
