# Generated by Django 2.1 on 2020-04-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailypost', '0008_auto_20200420_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codemodel',
            name='url',
        ),
        migrations.AddField(
            model_name='codemodel',
            name='img',
            field=models.ImageField(default=' ', upload_to='media'),
        ),
    ]
