# Generated by Django 2.1 on 2020-04-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailypost', '0011_remove_codemodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='codemodel',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
