# Generated by Django 2.1 on 2020-06-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailypost', '0012_codemodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='codemodel',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codemodel',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailypost',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailypost',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='codemodel',
            name='hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='codemodel',
            name='minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailypost',
            name='open_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='dailypost',
            name='student_id',
            field=models.CharField(max_length=32),
        ),
    ]
