# Generated by Django 2.1 on 2020-09-14 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailypost', '0013_auto_20200603_0844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='codemodel',
        ),
        migrations.DeleteModel(
            name='dailypost',
        ),
        migrations.DeleteModel(
            name='Totalpost',
        ),
    ]
