# Generated by Django 2.1 on 2020-06-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('post_time', models.DateTimeField()),
                ('distance', models.FloatField()),
                ('time_cost', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.IntegerField()),
                ('end_point', models.IntegerField()),
                ('open_id', models.CharField(max_length=32, unique=True)),
                ('student_id', models.CharField(max_length=32, unique=True)),
                ('ip', models.GenericIPAddressField(default=' ')),
            ],
        ),
    ]
