# Generated by Django 2.1 on 2020-06-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='point',
            name='post_time',
        ),
        migrations.RemoveField(
            model_name='point',
            name='time_cost',
        ),
    ]
