# Generated by Django 2.1 on 2020-06-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0003_auto_20200604_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trace',
            name='open_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='trace',
            name='student_id',
            field=models.CharField(max_length=32),
        ),
    ]
