# Generated by Django 2.1 on 2020-07-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0004_auto_20200604_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='runTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.IntegerField()),
                ('end_point', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='trace',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trace',
            name='time_cost',
            field=models.IntegerField(default=0),
        ),
    ]
