# Generated by Django 2.1 on 2020-07-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0005_auto_20200720_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trace',
            name='month',
            field=models.IntegerField(default=0),
        ),
    ]
