# Generated by Django 2.1 on 2020-07-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0006_auto_20200720_1325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.DeleteModel(
            name='runTrace',
        ),
        migrations.DeleteModel(
            name='Trace',
        ),
    ]
