# Generated by Django 2.1 on 2020-08-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('run', '0007_auto_20200721_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=32, unique=True)),
                ('student_id', models.CharField(max_length=32, unique=True)),
                ('Total_time', models.IntegerField()),
            ],
        ),
    ]
