# Generated by Django 2.1 on 2020-09-14 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0008_totalpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalPost',
        ),
    ]
