# Generated by Django 2.1 on 2020-09-02 20:43

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', mdeditor.fields.MDTextField()),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('createman', models.CharField(max_length=32)),
            ],
        ),
    ]
