# Generated by Django 2.1 on 2020-03-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user_is_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_register',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
