# Generated by Django 2.1 on 2020-03-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20200314_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_register',
            field=models.BooleanField(default=True),
        ),
    ]
