# Generated by Django 2.1 on 2020-04-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20200321_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='No', max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(default='No', max_length=32, unique=True),
        ),
    ]
