# Generated by Django 2.1 on 2020-04-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20200410_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='No', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(default='No', max_length=32),
        ),
    ]
