# Generated by Django 2.1 on 2020-04-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20200415_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='No', max_length=32, unique=True),
        ),
    ]
