# Generated by Django 2.1 on 2020-04-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20200420_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='No', max_length=32),
        ),
    ]
