# Generated by Django 2.1 on 2020-09-14 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20200420_2029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
